/**
*package org.kie.kogito.legacy;
*
*import org.kie.kogito.legacy.LoanApplication;
*
*global Integer maxAmount;
*global String op;
*global java.util.List approvedApplications;
*
*rule SmallDepositApprove when
 *   $l: LoanApplication( applicant.age op 20, deposit < 1000, amount <= 2000 )
*then
*    modify($l) { setApproved(true) };
*end

*rule CollectApprovedApplication when
*    $l: LoanApplication( approved )
*then
*    approvedApplications.add($l);
*end
**/